upgrade to Vaadin 8.13.0 w/ compatibility deps
run migration util and apply manual fixes

downgrade to Vaadin 8.7.1

a (failed) attempt to resolve the NoSuchMethodError: void com.vaadin.ui.UI.addDetachListener

don't bother excluding non-compat modules from vaadin-client-compiler (they're transitive from the compat modules anyway)

add vaadin-compatibility-shared

use a replacement UIScope (former addon dep did not appear to be compatible w/ Vaadin 8)

undid conversion to setReadOnly() - did not behave as I expected, so left old instruction commented out for now